
# Return True if targetSum can be generated by any combination of numbers in 'numbers' array
# Otherwise return false
# Numbers can be reused
def canSum(targetSum, numbers, memo = {}):
    
    if targetSum in memo:
        return memo[targetSum]
    if targetSum == 0:
        return True
    if targetSum < 0:
        return False
    

    for number in numbers:
        if canSum(targetSum - number, numbers, memo) == True:
            memo[targetSum] = True

            return True

    memo[targetSum] = False
    return False

    

print(canSum(7, [5, 3, 4], {}))
print(canSum(104, [17, 12, 4, 69, 7], {}))
print(canSum(7, [2, 4], {}))
print(canSum(300, [7, 14], {}))